services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env  
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db  # Use 'db' as the service name for the database
      - DB_PORT=${DB_PORT}
    env_file:
      - .env  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: