# Generated by Django 5.1.6 on 2025-03-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_section', models.CharField(help_text='e.g., EngineeringCycle-2_Year-Class_A', max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='training/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Image',
                'verbose_name_plural': 'Student Images',
                'db_table': 'student_image',
            },
        ),
    ]
