# Generated by Django 5.1.7 on 2025-03-11 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_parent'),
        ('students', '0002_studentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.RemoveField(
            model_name='studentimage',
            name='promo_section',
        ),
        migrations.AddField(
            model_name='student',
            name='section_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class'),
        ),
    ]
