# Generated by Django 5.1.7 on 2025-03-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_cycle_remove_student_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentImage',
        ),
    ]
