# Generated by Django 5.1.7 on 2025-03-12 23:30

import apps.studentimages.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_delete_studentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=apps.studentimages.models.student_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Image',
                'verbose_name_plural': 'Student Images',
                'db_table': 'student_image',
            },
        ),
    ]
