# Generated by Django 4.2.20 on 2025-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimage',
            name='is_encoded',
            field=models.BooleanField(default=False),
        ),
    ]
